apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e-app
  namespace: e2e-app
  labels:
    app: e2e-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: e2e-app
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    maxUnavailable: 1
  template:
    metadata:
      labels:
        app: e2e-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                - e2e-app
            topologyKey: "kubernetes.io/ip"
      containers:
      - name: e2e-app
        image: quay.io/giantswarm/e2e-app:[[ .SHA ]]
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      serviceAccountName: e2e-app
